[package]
name = "rscan-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
anyhow.workspace = true
rscan-config = { path = "../config" }
rscan-core = { path = "../core" }
rscan-output = { path = "../output" }
serde_json.workspace = true

[dev-dependencies]
hex.workspace = true
russh.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
tokio = { workspace = true, features = ["net", "rt-multi-thread", "time"] }

[[bin]]
name = "rscan"
path = "src/main.rs"
