[package]
name = "rscan-plugins"
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
aes = "0.8.4"
anyhow.workspace = true
base64.workspace = true
cbc = "0.1.2"
des = "0.8.1"
hex.workspace = true
md5 = "0.7.0"
oracle-rs = "0.1.7"
rdp-rs = "0.1.0"
reqwest = { workspace = true, features = ["blocking", "gzip", "rustls-tls"] }
rustls.workspace = true
serde_json.workspace = true
sha1 = "0.10.6"
smb2 = "0.7.2"
ssh2 = "0.9.5"
tokio = { workspace = true, features = ["rt-multi-thread", "time"] }

[dev-dependencies]
russh.workspace = true
rustls-pemfile.workspace = true
