use crate::{PluginDefinition, Transport};

pub(crate) const REGISTERED_PLUGINS: &[PluginDefinition] = &[
    PluginDefinition {
        key: "ftp",
        name: "FTP",
        ports: &[21],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "ssh",
        name: "SSH",
        ports: &[22, 2222],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "smb",
        name: "SMB",
        ports: &[445],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "smb2",
        name: "SMB2",
        ports: &[445],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "telnet",
        name: "Telnet",
        ports: &[23],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "rdp",
        name: "RDP",
        ports: &[3389, 13389, 33389],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "findnet",
        name: "FindNet",
        ports: &[135],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "netbios",
        name: "NetBIOS",
        ports: &[139],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "smtp",
        name: "SMTP",
        ports: &[25, 465, 587],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "imap",
        name: "IMAP",
        ports: &[143, 993],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "pop3",
        name: "POP3",
        ports: &[110, 995],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "activemq",
        name: "ActiveMQ",
        ports: &[61613],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "rsync",
        name: "Rsync",
        ports: &[873],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "rabbitmq",
        name: "RabbitMQ",
        ports: &[5672, 5671, 15672, 15671],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "mongodb",
        name: "MongoDB",
        ports: &[27017, 27018],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "modbus",
        name: "Modbus",
        ports: &[502, 5020],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "ldap",
        name: "LDAP",
        ports: &[389, 636],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "vnc",
        name: "VNC",
        ports: &[5900, 5901, 5902],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "ms17010",
        name: "MS17010",
        ports: &[445],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "smbghost",
        name: "SMBGhost",
        ports: &[445],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "kafka",
        name: "Kafka",
        ports: &[9092, 9093],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "mssql",
        name: "MSSQL",
        ports: &[1433, 1434],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "oracle",
        name: "Oracle",
        ports: &[1521, 1522, 1526],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "mysql",
        name: "MySQL",
        ports: &[3306, 3307, 13306, 33306],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "postgres",
        name: "PostgreSQL",
        ports: &[5432, 5433],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "neo4j",
        name: "Neo4j",
        ports: &[7687],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "cassandra",
        name: "Cassandra",
        ports: &[9042],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "snmp",
        name: "SNMP",
        ports: &[161, 162],
        transport: Transport::Udp,
    },
    PluginDefinition {
        key: "redis",
        name: "Redis",
        ports: &[6379, 6380, 16379],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "memcached",
        name: "Memcached",
        ports: &[11211],
        transport: Transport::Tcp,
    },
    PluginDefinition {
        key: "elasticsearch",
        name: "Elasticsearch",
        ports: &[9200, 9300],
        transport: Transport::Tcp,
    },
];
