pub const RULES: &[(&str, &str, &str)] = &[
    ("宝塔", "code", r#"(app.bt.cn/static/app.png|安全入口校验失败|<title>入口校验失败</title>|href="http://www.bt.cn/bbs)"#),
    ("深信服防火墙类产品", "code", r#"(SANGFOR FW)"#),
    ("360网站卫士", "code", r#"(webscan.360.cn/status/pai/hash|wzws-waf-cgi|zhuji.360.cn/guard/firewall/stopattack.html)"#),
    ("360网站卫士", "headers", r#"(360wzws|CWAP-waf|zhuji.360.cn|X-Safe-Firewall)"#),
    ("绿盟防火墙", "code", r#"(NSFOCUS NF)"#),
    ("绿盟防火墙", "headers", r#"(NSFocus)"#),
    ("Topsec-Waf", "index", r#"(<META NAME="Copyright" CONTENT="Topsec Network Security Technology Co.,Ltd"/>","<META NAME="DESCRIPTION" CONTENT="Topsec web UI"/>)"#),
    ("Anquanbao", "headers", r#"(Anquanbao)"#),
    ("BaiduYunjiasu", "headers", r#"(yunjiasu)"#),
    ("BigIP", "headers", r#"(BigIP|BIGipServer)"#),
    ("BinarySEC", "headers", r#"(binarysec)"#),
    ("BlockDoS", "headers", r#"(BlockDos.net)"#),
    ("CloudFlare", "headers", r#"(cloudflare)"#),
    ("Cloudfront", "headers", r#"(cloudfront)"#),
    ("Comodo", "headers", r#"(Protected by COMODO)"#),
    ("IBM-DataPower", "headers", r#"(X-Backside-Transport)"#),
    ("DenyAll", "headers", r#"(sessioncookie=)"#),
    ("dotDefender", "headers", r#"(dotDefender)"#),
    ("Incapsula", "headers", r#"(X-CDN|Incapsula)"#),
    ("Jiasule", "headers", r#"(jsluid=)"#),
    ("KONA", "headers", r#"(AkamaiGHost)"#),
    ("ModSecurity", "headers", r#"(Mod_Security|NOYB)"#),
    ("NetContinuum", "headers", r#"(Cneonction|nnCoection|citrix_ns_id)"#),
    ("Newdefend", "headers", r#"(newdefend)"#),
    ("Safe3", "headers", r#"(Safe3WAF|Safe3 Web Firewall)"#),
    ("Safedog", "code", r#"(404.safedog.cn/images/safedogsite/broswer_logo.jpg)"#),
    ("Safedog", "headers", r#"(Safedog|WAF/2.0)"#),
    ("SonicWALL", "headers", r#"(SonicWALL)"#),
    ("Stingray", "headers", r#"(X-Mapping-)"#),
    ("Sucuri", "headers", r#"(Sucuri/Cloudproxy)"#),
    ("Usp-Sec", "headers", r#"(Secure Entry Server)"#),
    ("Varnish", "headers", r#"(varnish)"#),
    ("Wallarm", "headers", r#"(wallarm)"#),
    ("阿里云", "code", r#"(errors.aliyun.com)"#),
    ("WebKnight", "headers", r#"(WebKnight)"#),
    ("Yundun", "headers", r#"(YUNDUN)"#),
    ("Yunsuo", "headers", r#"(yunsuo)"#),
    ("Coding pages", "header", r#"(Coding Pages)"#),
    ("启明防火墙", "code", r#"(/cgi-bin/webui?op=get_product_model)"#),
    ("Shiro", "headers", r#"(=deleteMe|rememberMe=)"#),
    ("Portainer(Docker管理)", "code", r#"(portainer.updatePassword|portainer.init.admin)"#),
    ("Gogs简易Git服务", "cookie", r#"(i_like_gogs)"#),
    ("Gitea简易Git服务", "cookie", r#"(i_like_gitea)"#),
    ("Nexus", "code", r#"(Nexus Repository Manager)"#),
    ("Nexus", "cookie", r#"(NX-ANTI-CSRF-TOKEN)"#),
    ("Harbor", "code", r#"(<title>Harbor</title>)"#),
    ("Harbor", "cookie", r#"(harbor-lang)"#),
    ("禅道", "code", r#"(/theme/default/images/main/zt-logo.png|/zentao/theme/zui/css/min.css)"#),
    ("禅道", "cookie", r#"(zentaosid)"#),
    ("协众OA", "code", r#"(Powered by 协众OA)"#),
    ("协众OA", "cookie", r#"(CNOAOASESSID)"#),
    ("xxl-job", "code", r#"(分布式任务调度平台XXL-JOB)"#),
    ("atmail-WebMail", "cookie", r#"(atmail6)"#),
    ("atmail-WebMail", "code", r#"(/index.php/mail/auth/processlogin|Powered by Atmail)"#),
    ("weblogic", "code", r#"(/console/framework/skins/wlsconsole/images/login_WebLogic_branding.png|Welcome to Weblogic Application Server|<i>Hypertext Transfer Protocol -- HTTP/1.1</i>)"#),
    ("致远OA", "code", r#"(/seeyon/common/|/seeyon/USER-DATA/IMAGES/LOGIN/login.gif)"#),
    ("discuz", "code", r#"(content="Discuz! X")"#),
    ("Typecho", "code", r#"(Typecho</a>)"#),
    ("金蝶EAS", "code", r#"(easSessionId)"#),
    ("phpMyAdmin", "cookie", r#"(pma_lang|phpMyAdmin)"#),
    ("phpMyAdmin", "code", r#"(/themes/pmahomme/img/logo_right.png)"#),
    ("H3C-AM8000", "code", r#"(AM8000)"#),
    ("360企业版", "code", r#"(360EntWebAdminMD5Secret)"#),
    ("H3C公司产品", "code", r#"(service@h3c.com)"#),
    ("H3C ICG 1000", "code", r#"(ICG 1000系统管理)"#),
    ("Citrix-Metaframe", "code", r#"(window.location="/Citrix/MetaFrame)"#),
    ("H3C ER5100", "code", r#"(ER5100系统管理)"#),
    ("阿里云CDN", "code", r#"(cdn.aliyuncs.com)"#),
    ("CISCO_EPC3925", "code", r#"(Docsis_system)"#),
    ("CISCO ASR", "code", r#"(CISCO ASR)"#),
    ("H3C ER3200", "code", r#"(ER3200系统管理)"#),
    ("万户oa", "code", r#"(/defaultroot/templates/template_system/common/css/|/defaultroot/scripts/|css/css_whir.css)"#),
    ("Spark_Master", "code", r#"(Spark Master at)"#),
    ("华为_HUAWEI_SRG2220", "code", r#"(HUAWEI SRG2220)"#),
    ("蓝凌OA", "code", r#"(/scripts/jquery.landray.common.js)"#),
    ("深信服ssl-vpn", "code", r#"(login_psw.csp)"#),
    ("华为 NetOpen", "code", r#"(/netopen/theme/css/inFrame.css)"#),
    ("Citrix-Web-PN-Server", "code", r#"(Citrix Web PN Server)"#),
    ("juniper_vpn", "code", r#"(welcome.cgi?p=logo|/images/logo_juniper_reversed.gif)"#),
    ("360主机卫士", "headers", r#"(zhuji.360.cn)"#),
    ("Nagios", "headers", r#"(Nagios Access)"#),
    ("H3C ER8300", "code", r#"(ER8300系统管理)"#),
    ("Citrix-Access-Gateway", "code", r#"(Citrix Access Gateway)"#),
    ("华为 MCU", "code", r#"(McuR5-min.js)"#),
    ("TP-LINK Wireless WDR3600", "code", r#"(TP-LINK Wireless WDR3600)"#),
    ("泛微OA", "headers", r#"(ecology_JSessionid)"#),
    ("泛微OA", "code", r#"(/spa/portal/public/index.js)"#),
    ("华为_HUAWEI_ASG2050", "code", r#"(HUAWEI ASG2050)"#),
    ("360网站卫士", "code", r#"(360wzb)"#),
    ("Citrix-XenServer", "code", r#"(Citrix Systems, Inc. XenServer)"#),
    ("H3C ER2100V2", "code", r#"(ER2100V2系统管理)"#),
    ("zabbix", "cookie", r#"(zbx_sessionid)"#),
    ("zabbix", "code", r#"(images/general/zabbix.ico|Zabbix SIA|zabbix-server: Zabbix)"#),
    ("CISCO_VPN", "headers", r#"(webvpn)"#),
    ("360站长平台", "code", r#"(360-site-verification)"#),
    ("H3C ER3108GW", "code", r#"(ER3108GW系统管理)"#),
    ("o2security_vpn", "headers", r#"(client_param=install_active)"#),
    ("H3C ER3260G2", "code", r#"(ER3260G2系统管理)"#),
    ("H3C ICG1000", "code", r#"(ICG1000系统管理)"#),
    ("CISCO-CX20", "code", r#"(CISCO-CX20)"#),
    ("H3C ER5200", "code", r#"(ER5200系统管理)"#),
    ("linksys-vpn-bragap14-parintins", "code", r#"(linksys-vpn-bragap14-parintins)"#),
    ("360网站卫士常用前端公共库", "code", r#"(libs.useso.com)"#),
    ("H3C ER3100", "code", r#"(ER3100系统管理)"#),
    ("H3C-SecBlade-FireWall", "code", r#"(js/MulPlatAPI.js)"#),
    ("360webfacil_360WebManager", "code", r#"(publico/template/)"#),
    ("Citrix_Netscaler", "code", r#"(ns_af)"#),
    ("H3C ER6300G2", "code", r#"(ER6300G2系统管理)"#),
    ("H3C ER3260", "code", r#"(ER3260系统管理)"#),
    ("华为_HUAWEI_SRG3250", "code", r#"(HUAWEI SRG3250)"#),
    ("exchange", "code", r#"(/owa/auth.owa|Exchange Admin Center)"#),
    ("Spark_Worker", "code", r#"(Spark Worker at)"#),
    ("H3C ER3108G", "code", r#"(ER3108G系统管理)"#),
    ("Citrix-ConfProxy", "code", r#"(confproxy)"#),
    ("360网站安全检测", "code", r#"(webscan.360.cn/status/pai/hash)"#),
    ("H3C ER5200G2", "code", r#"(ER5200G2系统管理)"#),
    ("华为（HUAWEI）安全设备", "code", r#"(sweb-lib/resource/)"#),
    ("华为（HUAWEI）USG", "code", r#"(UI_component/commonDefine/UI_regex_define.js)"#),
    ("H3C ER6300", "code", r#"(ER6300系统管理)"#),
    ("华为_HUAWEI_ASG2100", "code", r#"(HUAWEI ASG2100)"#),
    ("TP-Link 3600 DD-WRT", "code", r#"(TP-Link 3600 DD-WRT)"#),
    ("NETGEAR WNDR3600", "code", r#"(NETGEAR WNDR3600)"#),
    ("H3C ER2100", "code", r#"(ER2100系统管理)"#),
    ("jira", "code", r#"(jira.webresources)"#),
    ("金和协同管理平台", "code", r#"(金和协同管理平台)"#),
    ("Citrix-NetScaler", "code", r#"(NS-CACHE)"#),
    ("linksys-vpn", "headers", r#"(linksys-vpn)"#),
    ("通达OA", "code", r#"(/static/images/tongda.ico|http://www.tongda2000.com|通达OA移动版|Office Anywhere)"#),
    ("华为（HUAWEI）Secoway设备", "code", r#"(Secoway)"#),
    ("华为_HUAWEI_SRG1220", "code", r#"(HUAWEI SRG1220)"#),
    ("H3C ER2100n", "code", r#"(ER2100n系统管理)"#),
    ("H3C ER8300G2", "code", r#"(ER8300G2系统管理)"#),
    ("金蝶政务GSiS", "code", r#"(/kdgs/script/kdgs.js)"#),
    ("Jboss", "code", r#"(Welcome to JBoss|jboss.css)"#),
    ("Jboss", "headers", r#"(JBoss)"#),
    ("泛微E-mobile", "code", r#"(Weaver E-mobile|weaver,e-mobile)"#),
    ("泛微E-mobile", "headers", r#"(EMobileServer)"#),
    ("齐治堡垒机", "code", r#"(logo-icon-ico72.png|resources/themes/images/logo-login.png)"#),
    ("ThinkPHP", "headers", r#"(ThinkPHP)"#),
    ("ThinkPHP", "code", r#"(/Public/static/js/)"#),
    ("weaver-ebridge", "code", r#"(e-Bridge,http://wx.weaver)"#),
    ("Laravel", "headers", r#"(laravel_session)"#),
    ("DWR", "code", r#"(dwr/engine.js)"#),
    ("swagger_ui", "code", r#"(swagger-ui/css|"swagger":|swagger-ui.min.js)"#),
    ("大汉版通发布系统", "code", r#"(大汉版通发布系统|大汉网络)"#),
    ("druid", "code", r#"(druid.index|DruidDrivers|DruidVersion|Druid Stat Index)"#),
    ("Jenkins", "code", r#"(Jenkins)"#),
    ("红帆OA", "code", r#"(iOffice)"#),
    ("VMware vSphere", "code", r#"(VMware vSphere)"#),
    ("打印机", "code", r#"(打印机|media/canon.gif)"#),
    ("finereport", "code", r#"(isSupportForgetPwd|FineReport,Web Reporting Tool)"#),
    ("蓝凌OA", "code", r#"(蓝凌软件|StylePath:"/resource/style/default/"|/resource/customization|sys/ui/extend/theme/default/style/profile.css|sys/ui/extend/theme/default/style/icon.css)"#),
    ("GitLab", "code", r#"(href="https://about.gitlab.com/)"#),
    ("Jquery-1.7.2", "code", r#"(/webui/js/jquerylib/jquery-1.7.2.min.js)"#),
    ("Hadoop Applications", "code", r#"(/cluster/app/application)"#),
    ("海昌OA", "code", r#"(/loginmain4/js/jquery.min.js)"#),
    ("帆软报表", "code", r#"(WebReport/login.html|ReportServer)"#),
    ("帆软报表", "headers", r#"(数据决策系统)"#),
    ("华夏ERP", "headers", r#"(华夏ERP)"#),
    ("金和OA", "cookie", r#"(ASPSESSIONIDSSCDTDBS)"#),
    ("久其财务报表", "code", r#"(netrep/login.jsp|/netrep/intf)"#),
    ("若依管理系统", "code", r#"(ruoyi/login.js|ruoyi/js/ry-ui.js)"#),
    ("启莱OA", "code", r#"(js/jQselect.js|js/jquery-1.4.2.min.js)"#),
    ("智慧校园管理系统", "code", r#"(DC_Login/QYSignUp)"#),
    ("JQuery-1.7.2", "code", r#"(webui/js/jquerylib/jquery-1.7.2.min.js)"#),
    ("浪潮 ClusterEngineV4.0", "code", r#"(0;url=module/login/login.html)"#),
    ("会捷通云视讯平台", "code", r#"(him/api/rest/v1.0/node/role|him.app)"#),
    ("源码泄露账号密码 F12查看", "code", r#"(get_dkey_passwd)"#),
    ("Smartbi Insight", "code", r#"(smartbi.gcf.gcfutil)"#),
    ("汉王人脸考勤管理系统", "code", r#"(汉王人脸考勤管理系统|/Content/image/hanvan.png|/Content/image/hvicon.ico)"#),
    ("亿赛通-电子文档安全管理系统", "code", r#"(电子文档安全管理系统|/CDGServer3/index.jsp|/CDGServer3/SysConfig.jsp|/CDGServer3/help/getEditionInfo.jsp)"#),
    ("天融信 TopApp-LB 负载均衡系统", "code", r#"(TopApp-LB 负载均衡系统)"#),
    ("中新金盾信息安全管理系统", "code", r#"(中新金盾信息安全管理系统|中新网络信息安全股份有限公司)"#),
    ("好视通", "code", r#"(深圳银澎云计算有限公司|itunes.apple.com/us/app/id549407870|hao-shi-tong-yun-hui-yi-yuan)"#),
    ("蓝海卓越计费管理系统", "code", r#"(蓝海卓越计费管理系统|星锐蓝海网络科技有限公司)"#),
    ("和信创天云桌面系统", "code", r#"(和信下一代云桌面VENGD|/vesystem/index.php)"#),
    ("金山", "code", r#"(北京猎鹰安全科技有限公司|金山终端安全系统V9.0Web控制台|北京金山安全管理系统技术有限公司|金山V8)"#),
    ("WIFISKY-7层流控路由器", "code", r#"(深圳市领空技术有限公司|WIFISKY 7层流控路由器)"#),
    ("MetInfo-米拓建站", "code", r#"(MetInfo|/skin/style/metinfo.css|/skin/style/metinfo-v2.css)"#),
    ("IBM-Lotus-Domino", "code", r#"(/mailjump.nsf|/domcfg.nsf|/names.nsf|/homepage.nsf)"#),
    ("APACHE-kylin", "code", r#"(url=kylin)"#),
    ("C-Lodop打印服务系统", "code", r#"(/CLodopfuncs.js|www.c-lodop.com)"#),
    ("HFS", "code", r#"(href="http://www.rejetto.com/hfs/)"#),
    ("Jellyfin", "code", r#"(content="http://jellyfin.org")"#),
    ("FIT2CLOUD-JumpServer-堡垒机", "code", r#"(<title>JumpServer</title>)"#),
    ("Alibaba Nacos", "code", r#"(<title>Nacos</title>)"#),
    ("Nagios", "headers", r#"(nagios admin)"#),
    ("Pulse Connect Secure", "code", r#"(/dana-na/imgs/space.gif)"#),
    ("h5ai", "code", r#"(powered by h5ai)"#),
    ("jeesite", "cookie", r#"(jeesite.session.id)"#),
    ("拓尔思SSO", "cookie", r#"(trsidsssosessionid)"#),
    ("拓尔思WCMv7/6", "cookie", r#"(com.trs.idm.coSessionId)"#),
    ("天融信脆弱性扫描与管理系统", "code", r#"(/js/report/horizontalReportPanel.js)"#),
    ("天融信网络审计系统", "code", r#"(onclick=dlg_download())"#),
    ("天融信日志收集与分析系统", "code", r#"(天融信日志收集与分析系统)"#),
    ("URP教务系统", "code", r#"(北京清元优软科技有限公司)"#),
    ("科来RAS", "code", r#"(科来软件 版权所有|i18ninit.min.js)"#),
    ("正方OA", "code", r#"(zfoausername)"#),
    ("希尔OA", "code", r#"(/heeroa/login.do)"#),
    ("泛普建筑工程施工OA", "code", r#"(/dwr/interface/LoginService.js)"#),
    ("中望OA", "code", r#"(/IMAGES/default/first/xtoa_logo.png|/app_qjuserinfo/qjuserinfoadd.jsp)"#),
    ("海天OA", "code", r#"(HTVOS.js)"#),
    ("信达OA", "code", r#"(http://www.xdoa.cn</a>)"#),
    ("任我行CRM", "code", r#"(CRM_LASTLOGINUSERKEY)"#),
    ("Spammark邮件信息安全网关", "code", r#"(/cgi-bin/spammark?empty=1)"#),
    ("winwebmail", "code", r#"(WinWebMail Server|images/owin.css)"#),
    ("浪潮政务系统", "code", r#"(LangChao.ECGAP.OutPortal|OnlineQuery/QueryList.aspx)"#),
    ("天融信防火墙", "code", r#"(/cgi/maincgi.cgi)"#),
    ("网神防火墙", "code", r#"(css/lsec/login.css)"#),
    ("帕拉迪统一安全管理和综合审计系统", "code", r#"(module/image/pldsec.css)"#),
    ("蓝盾BDWebGuard", "code", r#"(BACKGROUND: url(images/loginbg.jpg) #e5f1fc)"#),
    ("Huawei SMC", "code", r#"(Script/SmcScript.js?version=)"#),
    ("coremail", "code", r#"(/coremail/bundle/|contextRoot: "/coremail"|coremail/common)"#),
    ("activemq", "code", r#"(activemq_logo|Manage ActiveMQ broker)"#),
    ("锐捷网络", "code", r#"(static/img/title.ico|support.ruijie.com.cn|Ruijie - NBR|eg.login.loginBtn)"#),
    ("禅道", "code", r#"(/theme/default/images/main/zt-logo.png|zentaosid)"#),
    ("weblogic", "code", r#"(/console/framework/skins/wlsconsole/images/login_WebLogic_branding.png|Welcome to Weblogic Application Server|<i>Hypertext Transfer Protocol -- HTTP/1.1</i>|<TITLE>Error 404--Not Found</TITLE>|Welcome to Weblogic Application Server|<title>Oracle WebLogic Server 管理控制台</title>)"#),
    ("weblogic", "headers", r#"(WebLogic)"#),
    ("致远OA", "code", r#"(/seeyon/USER-DATA/IMAGES/LOGIN/login.gif|/seeyon/common/)"#),
    ("蓝凌EIS智慧协同平台", "code", r#"(/scripts/jquery.landray.common.js)"#),
    ("深信服ssl-vpn", "code", r#"(login_psw.csp|loginPageSP/loginPrivacy.js|/por/login_psw.csp)"#),
    ("Struts2", "code", r#"(org.apache.struts2|Struts Problem Report|struts.devMode|struts-tags|There is no Action mapped for namespace)"#),
    ("泛微OA", "code", r#"(/spa/portal/public/index.js|wui/theme/ecology8/page/images/login/username_wev8.png|/wui/index.html#/?logintype=1)"#),
    ("Swagger UI", "code", r#"(/swagger-ui.css|swagger-ui-bundle.js|swagger-ui-standalone-preset.js)"#),
    ("金蝶政务GSiS", "code", r#"(/kdgs/script/kdgs.js|HTML5/content/themes/kdcss.min.css|/ClientBin/Kingdee.BOS.XPF.App.xap)"#),
    ("蓝凌OA", "code", r#"(蓝凌软件|StylePath:"/resource/style/default/"|/resource/customization|sys/ui/extend/theme/default/style/icon.css|sys/ui/extend/theme/default/style/profile.css)"#),
    ("用友NC", "code", r#"(Yonyou UAP|YONYOU NC|/Client/Uclient/UClient.dmg|logo/images/ufida_nc.png|iufo/web/css/menu.css|/System/Login/Login.asp?AppID=|/nc/servlet/nc.ui.iufo.login.Index)"#),
    ("用友IUFO", "code", r#"(iufo/web/css/menu.css)"#),
    ("TELEPORT堡垒机", "code", r#"(/static/plugins/blur/background-blur.js)"#),
    ("JEECMS", "code", r#"(/r/cms/www/red/js/common.js|/r/cms/www/red/js/indexshow.js|Powered by JEECMS|JEECMS|/jeeadmin/jeecms/index.do)"#),
    ("CMS", "code", r#"(Powered by .*CMS)"#),
    ("目录遍历", "code", r#"(Directory listing for /)"#),
    ("ATLASSIAN-Confluence", "code", r#"(com.atlassian.confluence)"#),
    ("ATLASSIAN-Confluence", "headers", r#"(X-Confluence)"#),
    ("向日葵", "code", r#"({"success":false,"msg":"Verification failure"})"#),
    ("Kubernetes", "code", r#"(Kubernetes Dashboard</title>|Kubernetes Enterprise Manager|Mirantis Kubernetes Engine|Kubernetes Resource Report)"#),
    ("WordPress", "code", r#"(/wp-login.php?action=lostpassword|WordPress</title>)"#),
    ("RabbitMQ", "code", r#"(RabbitMQ Management)"#),
    ("dubbo", "headers", r#"(Basic realm="dubbo")"#),
    ("Spring env", "code", r#"(logback)"#),
    ("ueditor", "code", r#"(ueditor.all.js|UE.getEditor)"#),
    ("亿邮电子邮件系统", "code", r#"(亿邮电子邮件系统|亿邮邮件整体解决方案)"#),
];

pub const POC_ALIASES: &[(&str, &str)] = &[
    ("致远OA", "seeyon"),
    ("泛微OA", "weaver"),
    ("通达OA", "tongda"),
    ("蓝凌OA", "landray"),
    ("ThinkPHP", "thinkphp"),
    ("Nexus", "nexus"),
    ("齐治堡垒机", "qizhi"),
    ("weaver-ebridge", "weaver-ebridge"),
    ("weblogic", "weblogic"),
    ("zabbix", "zabbix"),
    ("VMware vSphere", "vmware"),
    ("Jboss", "jboss"),
    ("用友", "yongyou"),
    ("用友IUFO", "yongyou"),
    ("coremail", "coremail"),
    ("金山", "kingsoft"),
];
